{% set name = "simber" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/simber-{{ version }}.tar.gz
  sha256: 96e92ade81430c7650a0563cac7994673b9459cc7795a41297056b3f4fd4d909

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.0
    - setuptools
  run:
    - colorama
    - python >=3.0

test:
  imports:
    - simber
  commands:
    - pip check
  requires:
    - pip

about:
  dev_url: https://github.com/deepjyoti30/simber
  summary: Simple, minimal, powerful logging library for Python
  license: MIT
  license_file: LICENSE
  home: https://github.com/deepjyoti30/simber
  doc_url: https://simber.deepjyoti30.dev/
  description: This library is aimed as a simple, minimal yet powerful logging library for all Python apps. This logging library aims to take away all the disadvantages of using the default logging library and at the same time be feature filled so that the end user feels powerful using it.

extra:
  recipe-maintainers:
    - HeavyTony2
